# Generated by Django 3.2.5 on 2021-07-17 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayDinnerPlatter',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisplayPasta',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisplayRegularPizza',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping1SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping2SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping3SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping1LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping2LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping3LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisplaySalad',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisplaySicilianPizza',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping1SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping2SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping3SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping1LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping2LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping3LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisplaySub',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('XCheesePrice', models.FloatField(blank=True, default=0.5, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisplayTopping',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
                ('buy', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('XCheesePrice', models.FloatField(blank=True, default=0.5, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('size', models.BooleanField(default=False)),
                ('Xcheese', models.BooleanField(default=False)),
                ('orders', models.ManyToManyField(blank=True, related_name='subs0_dish', to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping1SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping2SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping3SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping1LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping2LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping3LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('size', models.BooleanField(default=False)),
                ('no_of_toppings', models.IntegerField(default=0)),
                ('orders', models.ManyToManyField(blank=True, related_name='sicilian_dish', to='orders.Order')),
                ('toppings', models.ManyToManyField(blank=True, related_name='sicilian_dish', to='orders.Topping')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orders', models.ManyToManyField(blank=True, related_name='salad_dish', to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping1SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping2SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping3SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping1LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping2LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping3LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('size', models.BooleanField(default=False)),
                ('no_of_toppings', models.IntegerField(default=0)),
                ('orders', models.ManyToManyField(blank=True, related_name='regular_dish', to='orders.Order')),
                ('toppings', models.ManyToManyField(blank=True, related_name='regular_dish', to='orders.Topping')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orders', models.ManyToManyField(blank=True, related_name='pasta_dish', to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('size', models.BooleanField(default=False)),
                ('orders', models.ManyToManyField(blank=True, related_name='dinnerplatter_dish', to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
